#!/bin/sh

ROOTIMG=/sdcard/root.img
DEBUG=1

if [ ! "$INITIALDONE" = "1" ]
then
	mount -t proc none /proc
	mount -t sysfs none /sys

	mount -t devtmpfs devtmpfs /dev
	mkdir -m 0755 /dev/pts
	mkdir /dev/pts
	mount -t devpts -o gid=5,mode=620 devpts /dev/pts

	INITIALDONE=1 exec /init >/dev/console 2>&1
fi

hang()
{
	echo "Unable to proceed - hanging..."

	echo "Mountpoints:"
	mount

	echo "Root:"
	ls /

	while [ true ]
	do
		echo >/dev/null
	done
}

cpRd2Rt()
{
	RDPATH=/$1
	RTPATH=/realroot/$1

	if [ ! -d $RDPATH ]
	then
		echo "WARNING: RD path '$RDPATH' doesn't exist"
		return 0
	fi

	mkdir -p $RTPATH
	[ ! $? -eq 0 ] && echo "Unable to mkdir $RTPATH" && hang

	cp -a $RDPATH/* $RTPATH/
	[ ! $? -eq 0 ] && echo "Unable to cp $RDPATH to root" && hang
}

mntRd2Rt()
{
	RDPATH=/$1

	if [ $# -gt 1]
	then
		RTPATH=/realroot/$2
	else
		RTPATH=/realroot/$1
	fi

	mkdir -p $RTPATH
	[ ! $? -eq 0 ] && echo "Unable to mkdir $RTPATH" && hang

	mount -o move $RDPATH $RTPATH
	[ ! $? -eq 0 ] && echo "Unable to move mount $RDPATH to root" && hang
}

echo "Axdroid booting..."

mkdir /sdcard
mount -t vfat -o async,noatime,nodiratime,umask=0000 /dev/mmcblk0p1 /sdcard
[ ! $? -eq 0 ] && echo "Unable to mount SD card!" && hang

mkdir /realroot
mount -o loop,noatime,nodiratime $ROOTIMG /realroot
[ ! $? -eq 0 ] && echo "Unable to mount root FS!" && hang

cpRd2Rt bin
cpRd2Rt sbin
cpRd2Rt usr/bin
cpRd2Rt usr/sbin

mntRd2Rt proc
mntRd2Rt sys
mntRd2Rt dev
mntRd2Rt sdcard mnt/sdcard

exec switch_root -c /dev/console /realroot /axdroid.sh

